-- Alterar tabela para adicionar novo campo

ALTER TABLE TIPOPRECO ADD VL_TAXA_ENTREGA VALOR;

ALTER TABLE PREVENDA ADD VL_TAXA_ENTREGA VALOR;

ALTER TABLE PREVENDA_ITEM ADD VL_TAXA_ENTREGA_RAT VALOR;