
DO $$
DECLARE 
    empresa_lo INTEGER;
    idseq BIGINT;
    idtipopreco FK;

BEGIN 
    SELECT ID_EMPRESA$LO FROM EMPRESA$LO WHERE CH_LOCAL = 'T' LIMIT 1 INTO empresa_lo;

    idtipopreco = '1-1';


    idseq = NEXTVAL('gen_reajuste');

    INSERT INTO REAJUSTE (ID_REAJUSTE, ID_EMPRESA, ID_SEQ, CH_EXCLUIDO, DS_USUARIO, REC_VERSION, ID_USUARIO_M, DT_EMISSAO, DS_MOTIVO, CH_SITUAC, CH_TIPO, DS_CAMPO, CH_REAJUSTE, VL_REAJUSTE, ID_TIPOPRECO, DS_FIL_GRUPOITEM, DS_FIL_MARCA, ID_FILIAL, CH_FIL_PRECO, CH_REM_PREDIF, DS_FIL_DS_ITEM, DS_FIL_ITEM, CH_LIBAGE, DH_LIBAGE, CH_LIBPEN, CH_ATUPRECAD, CH_FIL_ESTPOSI, CH_TIPOAGE, NR_TURNOAGE)
    VALUES (idseq || '-' || empresa_lo, empresa_lo, idseq, NULL, 'POSTGRES', '1', '1-1', '2021-07-15', NULL, 'L', 'C', 'PRECO', 'V', NULL, '1-1', NULL, NULL, '1', 'F', 'F', NULL, NULL, 'F', NULL, 'F', 'T', NULL, NULL, NULL);

END$$;