
DO $$
DECLARE 
    empresa_lo INTEGER;
    idseq BIGINT;
BEGIN 
    SELECT ID_EMPRESA$LO FROM EMPRESA$LO WHERE CH_LOCAL = 'T' LIMIT 1 INTO empresa_lo;

    idseq = NEXTVAL('gen_movence');

    INSERT INTO MOVENCE (ID_MOVENCE, ID_EMPRESA, ID_SEQ, CH_EXCLUIDO, DS_USUARIO, ID_BICO, DH_MOVENCE, QT_MOVIME, QT_ENCERRANTE_INI, QT_ENCERRANTE_FIM, ID_INTERVENCAO, ID_DOCFISCAL, ID_ABASTECIMENTO, ID_AFERICAO, ID_ITEM, CH_MANUAL, DS_HISTORICO)
    VALUES (idseq || '-' || empresa_lo, empresa_lo, idseq, NULL, 'POSTGRES', NULL, '2021-08-25 11:08:00', '10000', NULL, NULL, NULL, '1-1', NULL, NULL, '2-1', 'T', NULL);


END$$;