-- XPERT: ENTIDADES

SELECT 
	e.ID_ENTIDADE, 
	CASE
		WHEN (e.PESSOA = 1) THEN e.RAZAOSOCIALENTIDADE
		ELSE e.NOMEENTIDADE
	END NOME,
  e.CNPJCPF,
  CASE 
		WHEN (e.PESSOA = 0) THEN e.IERG
		ELSE NULL
	END RG,
  CASE 
		WHEN (e.PESSOA = 1) THEN e.IERG
		WHEN (e.PESSOA = 0) THEN e.IEFISICA
		ELSE NULL
	END IE, '' IE_MUNICIPAL,
	c.NOMEPAIS, c.UF, c.NOMECIDADE, e.ENDERECO, e.NUMERO, e.BAIRRO, e.CEP, 
	e.FONE, e.CELULAR, c.CODIGOCIDADE IBGE, 
  CONCAT(e.EMAIL, ';', e.EMAIL_COBRANCA, ';', e.EMAIL_NFE_NFCE) EMAIL,
  e.ATIVO
FROM dbo.ENTIDADES AS e
LEFT JOIN dbo.CIDADES c ON (e.ID_CIDADES = c.ID_CIDADES)