SELECT 
    en.DS_CPFCNPJ CNPJ, en.ds_entidade,
    (SELECT DS_VERSAO FROM EMPRESA$LO WHERE CH_LOCAL = 'T' LIMIT 1) DS_VERSAO
FROM ENTIDADE en
JOIN EMPRESA e ON (en.ID_ENTIDADE = e.ID_ENTIDADE)
WHERE e.ID_EMPRESA = (
    SELECT COALESCE(se.ID_FILIAL, se.ID_EMPRESA)
    FROM EMPRESA se 
    JOIN EMPRESA$LO sel ON (se.ID_EMPRESA = sel.ID_EMPRESA$LO)
    WHERE sel.CH_LOCAL = 'T'
    LIMIT 1
)