-- TODAS TRANSACOES AME

SELECT crp.*
FROM CONCIRECPAG crp
JOIN ESPECIE e ON (crp.ID_ESPECIE = e.ID_ESPECIE)
JOIN INTEGRACAO i ON (e.ID_INTEGRACAO_TEF = i.ID_INTEGRACAO)
WHERE crp.CH_EXCLUIDO IS NULL
AND i.DS_IDENTIFICADOR = 'AME'

-- QUANTIDADE DE TRANSACOES AME POR TIPO DE PDV

SELECT 
  COUNT(1) QUANTIDADE, 
  case
     when pv.CH_TIPO_PDV = 'M' then 'PDV MOVEL'
	 when pv.CH_TIPO_PDV = 'D' then 'DESKTOP'
  end TIPO_PDV
FROM CONCIRECPAG crp
JOIN DOCFISCAL d ON (crp.ID_DOCFISCAL = d.ID_DOCFISCAL)
JOIN PONTOVENDA pv ON (d.ID_PONTOVENDA = pv.ID_PONTOVENDA)
JOIN ESPECIE e ON (crp.ID_ESPECIE = e.ID_ESPECIE)
JOIN INTEGRACAO i ON (e.ID_INTEGRACAO_TEF = i.ID_INTEGRACAO)
WHERE crp.CH_EXCLUIDO IS NULL
AND i.DS_IDENTIFICADOR = 'AME'
GROUP BY 2