-- XPERT: GRUPOPRODUTOS (Retorna apenas os grupos que esto vinculados a algum produto)

SELECT gp.ID_GRUPOPRODUTOS, gp.NOMEGRUPOPRODUTOS
FROM dbo.GRUPOPRODUTOS gp
JOIN dbo.PRODUTOS p ON (gp.ID_GRUPOPRODUTOS = p.ID_GRUPOPRODUTOS)
GROUP BY gp.ID_GRUPOPRODUTOS, gp.NOMEGRUPOPRODUTOS
ORDER BY 1