--UPDATE

do $$declare
	IDimposto varchar(30);
begin

	IDimposto = ''; --INFORMAR AQUI ID DO IMPOSTO QUE DESEJA APROVEITAR CREDITOS

	UPDATE NFT_ITEM_IMPOSTO SET CH_APRCRE = 'T' 
	WHERE CH_APRCRE = 'F'
	AND ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = IDimposto)
	AND ID_NFT IN 
		(SELECT a.ID_NFT FROM NFT a
		JOIN NFT_ITEM_IMPOSTO b ON (A.ID_NFT=B.ID_NFT)
		JOIN NFT_ITEM c ON (b.ID_NFT=c.ID_NFT)
		WHERE b.CH_APRCRE = 'F'
		AND b.ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = IDimposto)
		AND b.ID_CST IN 
		(SELECT ID_CST FROM CST WHERE NR_CST IN ('','')) --INFORMAR AQUI OS NUMEROS DAS CST QUE PRECISA MARCAR, EX: ('010','020')
		AND a.CH_EXCLUIDO IS NULL);

end$$;

--CONSULTA

SELECT 
	COUNT(*)
FROM NFT_ITEM_IMPOSTO b
JOIN NFT a ON (A.ID_NFT=B.ID_NFT)
JOIN NFT_ITEM c ON (b.ID_NFT=c.ID_NFT)
	WHERE CH_APRCRE = 'F'
	AND a.CH_EXCLUIDO IS NULL
	AND ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = '6-1')
	AND a.ID_NFT IN 
	(SELECT a.ID_NFT FROM NFT a
		JOIN NFT_ITEM_IMPOSTO b ON (A.ID_NFT=B.ID_NFT)
		JOIN NFT_ITEM c ON (b.ID_NFT=c.ID_NFT)
		WHERE CH_APRCRE = 'F'
		AND a.CH_EXCLUIDO IS NULL
		AND b.ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = '6-1')
		AND b.ID_CST IN (SELECT ID_CST FROM CST WHERE NR_CST IN ('','','')))