/*
    ALTERAR CONTRAPARTIDA LANÇAMENTOS 
    IMPORTADOS PARA UMA CONTA GENERICA
*/

-- RETORNA LANCAMENTOS IMPORTADOS

SELECT 
    L.DH_LANC, l.ID_LANC, l.NR_DOCUME, l.ID_PLANOCONTA, p.DS_PLANOCONTA,    
    (
        SELECT  l_.ID_LANC || ' ' || l_.ID_PLANOCONTA || ' ' || p_.DS_PLANOCONTA
        FROM LANC l_ 
        LEFT JOIN PLANOCONTA p_ ON (l_.ID_PLANOCONTA = p_.ID_PLANOCONTA) 
			WHERE l_.ID_AGRU = l.ID_AGRU  
			AND l_.ID_LANC <> l.ID_LANC  
        ORDER BY l_.ID_SEQ
        LIMIT 1
    ) PLANOCONTA_CONTRAPARTIDA
FROM LANC l 
JOIN PLANOCONTA p ON (l.ID_PLANOCONTA = p.ID_PLANOCONTA)
	WHERE l.ID_FILIAL =:EMPRESA 
	AND l.CH_EXCLUIDO IS NULL 
	AND l.NR_DOCUME LIKE 'I%'
	AND p.NR_PLANOCONTA LIKE '01.03%'
	AND l.ID_TIPOLANC IS NULL  
	AND l.CH_DEBCRE = p.CH_NATUREZA  
	AND l.ID_LANC IN (
						SELECT NEW_ID FROM IMPID 
						WHERE DS_TABELA = 'LANC'
					)  
ORDER BY l.DH_LANC

-------------------------------------------------------------------

UPDATE LANC SET
    ID_PLANOCONTA = :ID_PLANOCONTA
WHERE ID_LANC IN (
    SELECT     
        (
            SELECT  l_.ID_LANC
            FROM LANC l_ 
            LEFT JOIN PLANOCONTA p_ ON (l_.ID_PLANOCONTA = p_.ID_PLANOCONTA) 
				WHERE l_.ID_AGRU = l.ID_AGRU
				AND l_.ID_LANC <> l.ID_LANC  
            ORDER BY l_.ID_SEQ
            LIMIT 1
        ) ID_PLANOCONTA_CONTRAPARTIDA
    FROM LANC l 
    JOIN PLANOCONTA p ON (l.ID_PLANOCONTA = p.ID_PLANOCONTA)
		WHERE l.ID_FILIAL =:EMPRESA 
		AND l.CH_EXCLUIDO IS NULL 
		AND l.NR_DOCUME LIKE 'I%'
		AND p.NR_PLANOCONTA LIKE '02.01%'
		AND l.ID_TIPOLANC IS NULL  
		AND l.CH_DEBCRE = p.CH_NATUREZA  
		AND l.ID_LANC IN (
							SELECT NEW_ID FROM IMPID 
							WHERE DS_TABELA = 'LANC'
						)  
ORDER BY l.DH_LANC

)