/*
* Lançamentos com data maior que a data de fechamento do caixa
*/
SELECT
CAST((cp.DT_ABERTURA || ' ' || cp.HR_ABERTURA) AS TIMESTAMP) DH_ABE_CAIXA,
CAST((cp.DT_FECHAMENTO || ' ' || cp.HR_FECHAMENTO) AS TIMESTAMP) DH_FEC_CAIXA,
l.DT_CAIXA, l.DT_DOC, l.DH_LANC
, l.*
FROM LANC l
JOIN CAIXAPDV cp ON (l.ID_CAIXAPDV = cp.ID_CAIXAPDV)
WHERE l.CH_EXCLUIDO IS NULL AND
cp.CH_SITUAC = 'F' AND
CAST(l.DH_LANC AS DATE) > cp.DT_FECHAMENTO


/*
* Seta data do lançamento igual a data de abertura
*/
UPDATE LANC l SET
DH_LANC = (
			SELECT CAST((c.DT_ABERTURA || ' ' || c.HR_ABERTURA) AS TIMESTAMP)
			FROM CAIXAPDV c WHERE c.ID_CAIXAPDV = l.ID_CAIXAPDV  
			)
WHERE l.CH_EXCLUIDO IS NULL
AND CAST(l.DH_LANC AS DATE) > (SELECT cp.DT_FECHAMENTO FROM CAIXAPDV cp WHERE cp.ID_CAIXAPDV = l.ID_CAIXAPDV AND cp.CH_SITUAC = 'F')