-- XPERT: PRODUTOS

SELECT 
	p.ID_PRODUTOS, p.NOMEPRODUTO, p.ID_GRUPOPRODUTOS, p.CODIGOBARRAPRODUTO, 
	CASE 
		WHEN (p.CUSTOGERENCIAL <> '0') THEN p.CUSTOGERENCIAL
		WHEN (p.CUSTOMEDIO <> '0') THEN p.CUSTOMEDIO
		ELSE 0.1
	END CUSTO,
	(
		SELECT TOP 1 CASE WHEN (pl.VALOR1 IS NULL) THEN '0' ELSE pl.VALOR1 END 
		FROM dbo.PRODUTOSPORLOCALVENDA pl 
		WHERE pl.ID_PRODUTOS = p.ID_PRODUTOS AND pl.VALOR1 > 0
	) PRECO_VENDA, 
	p.QTDENEGATIVA, p.UNIDADE, 
	p.NCM, p.CEST, p.CODIGOANP, p.ATIVO
FROM dbo.PRODUTOS p