-- RETORNA OS ITENS EXCLUIDOS QUE TEM ATUALIZAÇÃO DE CUSTO PENDENTE

SELECT * FROM ITEM
WHERE CH_EXCLUIDO = 'T' 
AND ID_ITEM IN (
  SELECT ID_ITEM FROM ATUCUSTO_ITEM WHERE DT_PROCESSADA IS NULL
)

-- RETORNA AS ATUALIZAÇÕES DE CUSTO PENDENTES COM ITENS EXCLUIDOS

SELECT * FROM ATUCUSTO
WHERE ID_ATUCUSTO IN (
  SELECT ID_ATUCUSTO FROM ATUCUSTO_ITEM 
  WHERE DT_PROCESSADA IS NULL AND ID_ITEM IN (
    SELECT ID_ITEM FROM ITEM WHERE CH_EXCLUIDO = 'T'
  )
)