-- UPDATE
UPDATE CONCIRECPAG c SET 
    NR_NSU = (
        SELECT CAST(t.NR_CODIGOUNICO AS VARCHAR(30))
        FROM TEF_OPE t WHERE t.ID_CARTAOTEF = c.ID_CARTAOTEF 
        AND t.ID_DOCFISCAL_BAIXA = c.ID_DOCFISCAL_BAIXA
    )
WHERE c.ID_CONCIRECPAG IN (
    SELECT c.ID_CONCIRECPAG
    FROM CONCIRECPAG c
    INNER JOIN TEF_OPE t ON (c.ID_CARTAOTEF = t.ID_CARTAOTEF AND c.ID_DOCFISCAL_BAIXA = t.ID_DOCFISCAL_BAIXA)
    WHERE c.CH_EXCLUIDO IS NULL AND 
        c.CH_SITUAC = 'A' AND
        c.CH_TEF = 'T' AND    
        t.NR_OPERATEF IN ('REDE') AND  
        c.ID_DOCFISCAL IN (
            SELECT d.ID_DOCFISCAL FROM DOCFISCAL d 
            INNER JOIN PONTOVENDA p ON (d.ID_PONTOVENDA = p.ID_PONTOVENDA)
            WHERE p.CH_TIPO_PDV = 'M' 
            --AND p.ID_PONTOVENDA = :ID_PONTOVENDA -- Filtro opicional, ja busca apenas pdv movel
            --AND p.ID_FILIAL = :ID_FILIAL -- Filtro opicional
        )
    );