DO $$
DECLARE

BEGIN

    UPDATE abastecimento SET ch_excluido = 'T', ch_ativo = 'F' WHERE ch_excluido IS NULL;
    UPDATE seriedoc SET ch_excluido = 'T', ch_ativo = 'F' WHERE ch_excluido IS NULL;
    UPDATE lanc SET ch_excluido = 'T', ch_ativo = 'F' WHERE ch_excluido IS NULL;
    UPDATE lanc_ban SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE lanc_det SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE lanc_hist SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE lanc_comiss SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE lanc_comiss_bai SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_docref SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_eletro SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_comp SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_cfgfiscal SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_comiss SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_infadic SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_imposto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_item_plano SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_reparc SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_prevenda SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_obs SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_imposto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_infadic SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_baixa SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_baixa_hist SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docfiscal_baixa_parc SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_item_imposto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_item_cfgfiscal SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_item_planoconta SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_item_localarm SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_imposto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE nft_ctnf SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE movest SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE movest_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE invent SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE invent_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE atucusto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE atucusto_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE caixapdv SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE caixapdv_bico SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE caixapdv_fec SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE caixapdv_fecusu SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE caixapdv_abe SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE conciliacao SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE conciliacao_movi SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE concirecpag SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE concirecpag_bai SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE conciven SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE conciven_det SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE intervencao SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE afericao SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE afericao_det SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE arqpaf SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE arqecf SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE arqintegracao SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE eqpecf SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE eqpecf_esp SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE eqpecf_integracao SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docecf SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE docecf_det SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE msgemail SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE msgemail_anexo SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE pagcomiss SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE pagcomiss_mov SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE parcela SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE parcela_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE prevenda SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE prevenda_item SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE prevenda_item_comp SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE rectopagto SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE rectopagto_baixa SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE rectopagto_recpag SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE reparc SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE reparc_cencus SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE reparc_docfiscal SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE reparc_obs SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE reparc_recpag SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE tef SET ch_excluido = 'T' WHERE ch_excluido IS NULL;
    UPDATE tef_ope SET ch_excluido = 'T' WHERE ch_excluido IS NULL;

END$$;