DO $$
DECLARE 
BEGIN

	UPDATE NFT_ITEM_IMPOSTO SET ID_CST = 'CODIGO_CST_CORRETA' 
	WHERE ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = 'CODIGO_IMPOSTO')
	AND ID_NFT IN 
		(SELECT a.ID_NFT FROM NFT a
		JOIN NFT_ITEM_IMPOSTO b ON (A.ID_NFT=B.ID_NFT)
		JOIN NFT_ITEM c ON (b.ID_NFT=c.ID_NFT)
		WHERE b.ID_IMPOSTO IN (SELECT ID_IMPOSTO FROM IMPOSTO WHERE ID_IMPOSTO = 'CODIGO_IMPOSTO')
		AND b.ID_CST IN (SELECT ID_CST FROM CST WHERE NR_CST = 'NR_CST_ERRADA')
		AND a.CH_EXCLUIDO IS NULL);

END$$;