DO $$
DECLARE
  l_id_empresa INTEGER;
  l_DOCECF FK;
  l_NR_COOINI NUMERIC;
  l_NR_COOFIM NUMERIC;
BEGIN

  SELECT ID_EMPRESA$LO FROM EMPRESA$LO WHERE CH_LOCAL = 'T' LIMIT 1 INTO l_id_empresa;

  FOR l_DOCECF, l_NR_COOINI, l_NR_COOFIM IN 
    SELECT ID_DOCECF, NR_COOINI, NR_COOFIM FROM DOCECF
        WHERE DS_TIPO = 'RZ' 
        AND NR_COOINI < '1000000'
        AND ID_FILIAL = '1'                                   -- PREENCHER APENAS COM O NÚMERO, EXEMPLO: 1 
        AND ID_EQPECF = '1-2'                                 -- PREENCHER COM O CÓDIGO DA IMPRESSORA, EXEMPLO: 1-1                                   
        AND DT_MOVIME BETWEEN '2021-03-01' AND '2021-03-31'   -- PREENCHER NO FORMATO: ANO-MES-DIA

  LOOP
    UPDATE DOCECF SET
      NR_COOINI = (l_NR_COOINI + '1000000'),
      NR_COOFIM = (l_NR_COOFIM + '1000000')
        WHERE ID_DOCECF = l_DOCECF;
  END LOOP;
END$$;