
INSERT INTO IMPID (id_impid, id_empresa, id_seq, DS_APLICATIVO,DS_TABELA,OLD_ID,NEW_ID) 

SELECT (id_seq + 999999) || '-' || id_empresa, id_empresa, id_seq + 999999,  'EXCEL','ENTIDADE', DS_CPFCNPJ,ID_ENTIDADE FROM ENTIDADE WHERE CH_EXCLUIDO IS NULL AND DS_CPFCNPJ IS NOT NULL